export interface PropFirm {
  slug: string;
  name: string;
  payoutProcessor: string;
  feeProcessor: string;
  detection: 'auto' | 'manual';
  description: string;
  typicalFees: string[];
  website: string;
  category: 'futures' | 'forex' | 'stocks' | 'multi';
}

export interface PayoutProcessor {
  slug: string;
  name: string;
  description: string;
}

export const firms: PropFirm[] = [
  { slug: 'topstep', name: 'Topstep', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'One of the largest futures prop firms, offering funded accounts after passing a Trading Combine evaluation.', typicalFees: ['Monthly subscription ($49-$149/mo)', 'Reset fee ($99)', 'Data feed fees'], website: 'https://www.topstep.com', category: 'futures' },
  { slug: 'ftmo', name: 'FTMO', payoutProcessor: 'Direct Bank Transfer', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A leading forex prop firm based in Prague, known for its two-step Challenge and Verification process.', typicalFees: ['Challenge fee ($155-$1,080)', 'Verification fee (included)', 'No recurring subscription'], website: 'https://www.ftmo.com', category: 'forex' },
  { slug: 'the5ers', name: 'The5%ers', payoutProcessor: 'Rise', feeProcessor: 'Credit card', detection: 'auto', description: 'A forex and metals prop firm offering instant funding and a scaling plan up to $4M in buying power.', typicalFees: ['Challenge fee ($95-$875)', 'No monthly subscription', 'No reset fees'], website: 'https://www.the5ers.com', category: 'forex' },
  { slug: 'apex-trader-funding', name: 'Apex Trader Funding', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A popular futures prop firm with straightforward evaluation rules and frequent promotional pricing.', typicalFees: ['Monthly evaluation fee ($147-$657/mo)', 'Activation fee ($85)', 'Data feed fees'], website: 'https://www.apextraderfunding.com', category: 'futures' },
  { slug: 'myfundedfutures', name: 'MyFundedFutures', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm focused on a simple one-step evaluation with fast payouts and trader-friendly rules.', typicalFees: ['Evaluation fee ($50-$300)', 'Reset fee', 'No monthly recurring fee'], website: 'https://www.myfundedfutures.com', category: 'futures' },
  { slug: 'earn2trade', name: 'Earn2Trade', payoutProcessor: 'Rise', feeProcessor: 'Credit card', detection: 'auto', description: 'A futures trading education and evaluation firm offering the Gauntlet Mini and Trader Career Path programs.', typicalFees: ['Monthly evaluation fee ($150-$350/mo)', 'Reset fee ($100)', 'Platform/data fees'], website: 'https://www.earn2trade.com', category: 'futures' },
  { slug: 'bulenox', name: 'Bulenox', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm offering affordable evaluations with straightforward rules and Rise payouts.', typicalFees: ['Monthly evaluation fee ($115-$535/mo)', 'Activation fee ($98)', 'Reset fee'], website: 'https://www.bulenox.com', category: 'futures' },
  { slug: 'tradeday', name: 'TradeDay', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A newer futures prop firm with competitive pricing, no daily drawdown limits, and fast evaluation passes.', typicalFees: ['Monthly evaluation fee ($99-$625/mo)', 'Activation fee', 'No reset fees'], website: 'https://www.tradeday.com', category: 'futures' },
  { slug: 'takeprofittrader', name: 'TakeProfitTrader', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures evaluation firm known for its PRO account structure and quick same-day payouts via Rise.', typicalFees: ['Monthly evaluation fee ($150-$360/mo)', 'Activation fee ($130)', 'Reset fee ($99)'], website: 'https://www.takeprofittrader.com', category: 'futures' },
  { slug: 'tradeify', name: 'Tradeify', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm offering a straightforward evaluation with no scaling rules and daily payouts.', typicalFees: ['Monthly evaluation fee ($100-$350/mo)', 'Activation fee', 'No reset fees'], website: 'https://www.tradeify.com', category: 'futures' },
  { slug: 'fundednext', name: 'FundedNext', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A multi-asset prop firm supporting forex and futures, offering up to 95% profit splits and multiple evaluation models.', typicalFees: ['Challenge fee ($32-$999)', 'No monthly subscription', 'No reset fees'], website: 'https://www.fundednext.com', category: 'multi' },
  { slug: 'leeloo-trading', name: 'Leeloo Trading', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm with multiple evaluation programs and an emphasis on trader development and risk management.', typicalFees: ['Monthly evaluation fee ($77-$675/mo)', 'Activation fee ($85)', 'Reset fee'], website: 'https://www.leelootrading.com', category: 'futures' },
  { slug: 'elite-trader-funding', name: 'Elite Trader Funding', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm offering fast evaluations with simple rules and one of the lowest activation fees in the industry.', typicalFees: ['Monthly evaluation fee ($80-$690/mo)', 'Activation fee ($80)', 'Reset fee ($75)'], website: 'https://www.elitetraderfunding.com', category: 'futures' },
  { slug: 'blusky-trading', name: 'BluSky Trading', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm offering evaluations with no minimum trading days and straightforward payout rules.', typicalFees: ['Monthly evaluation fee ($125-$535/mo)', 'Activation fee', 'Reset fee'], website: 'https://www.bluskytrading.com', category: 'futures' },
  { slug: 'surgetrader', name: 'SurgeTrader', payoutProcessor: 'Various', feeProcessor: 'Credit card', detection: 'auto', description: 'A multi-asset prop firm supporting forex, futures, and stocks with a one-phase audition process.', typicalFees: ['Audition fee ($200-$6,500)', 'No monthly subscription', 'No reset fees'], website: 'https://www.surgetrader.com', category: 'multi' },
  { slug: 'true-forex-funds', name: 'True Forex Funds', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A forex prop firm offering one-step and two-step evaluation programs with up to 80% profit splits.', typicalFees: ['Challenge fee ($59-$899)', 'No monthly subscription', 'No reset fees'], website: 'https://www.trueforexfunds.com', category: 'forex' },

  // Futures firms
  { slug: 'oneup-trader', name: 'OneUp Trader', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm offering a single-step evaluation with no scaling restrictions and Rise payouts.', typicalFees: ['Monthly evaluation fee ($125-$650/mo)', 'Activation fee', 'Reset fee'], website: 'https://www.oneuptrader.com', category: 'futures' },
  { slug: 'alpha-futures', name: 'Alpha Futures', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm with competitive evaluations and straightforward payout rules via Rise.', typicalFees: ['Evaluation fee', 'Activation fee', 'Data feed fees'], website: 'https://www.alphafutures.com', category: 'futures' },
  { slug: 'daytraders', name: 'DayTraders', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures-focused prop firm offering evaluations with competitive pricing and quick payouts.', typicalFees: ['Monthly evaluation fee', 'Activation fee', 'Data feed fees'], website: 'https://www.daytraders.com', category: 'futures' },
  { slug: 'legends-trading', name: 'Legends Trading', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm with evaluation programs designed for active day traders seeking funded accounts.', typicalFees: ['Evaluation fee', 'Activation fee', 'Reset fee'], website: 'https://www.legendstrading.com', category: 'futures' },
  { slug: 'funded-futures-network', name: 'Funded Futures Network', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm offering evaluations with no minimum trading days and Rise-based payouts.', typicalFees: ['Monthly evaluation fee', 'Activation fee', 'Reset fee'], website: 'https://www.fundedfuturesnetwork.com', category: 'futures' },
  { slug: 'uprofit', name: 'UProfit', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm with a one-step evaluation process and daily payouts through Rise.', typicalFees: ['Evaluation fee ($149-$649)', 'No activation fee', 'Reset fee'], website: 'https://www.uprofit.com', category: 'futures' },
  { slug: 'fundingticks', name: 'FundingTicks', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm offering evaluations with straightforward rules and competitive pricing.', typicalFees: ['Evaluation fee', 'Activation fee', 'Data feed fees'], website: 'https://www.fundingticks.com', category: 'futures' },
  { slug: 'dna-funded', name: 'DNA Funded', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm providing evaluation programs with transparent rules and Rise payouts.', typicalFees: ['Evaluation fee', 'Activation fee', 'Reset fee'], website: 'https://www.dnafunded.com', category: 'futures' },
  { slug: 'liberty-market-investments', name: 'Liberty Market Investments', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm offering funded accounts through a structured evaluation process.', typicalFees: ['Evaluation fee', 'Activation fee', 'Data feed fees'], website: 'https://www.libertymarketinvestments.com', category: 'futures' },
  { slug: 'top-one-futures', name: 'Top One Futures', payoutProcessor: 'Rise', feeProcessor: 'Stripe', detection: 'auto', description: 'A futures prop firm with evaluations designed for traders seeking funded accounts with Rise payouts.', typicalFees: ['Evaluation fee', 'Activation fee', 'Reset fee'], website: 'https://www.toponefutures.com', category: 'futures' },

  // Forex firms
  { slug: 'city-traders-imperium', name: 'City Traders Imperium', payoutProcessor: 'Wise', feeProcessor: 'Credit card', detection: 'auto', description: 'A London-based forex prop firm offering instant funding and evaluation programs with scaling up to $2M.', typicalFees: ['Challenge fee ($109-$899)', 'No monthly subscription', 'No reset fees'], website: 'https://www.citytradersimperium.com', category: 'forex' },
  { slug: 'traders-with-edge', name: 'Traders With Edge', payoutProcessor: 'Wise', feeProcessor: 'Credit card', detection: 'auto', description: 'A forex prop firm offering funded accounts with flexible evaluation options and competitive profit splits.', typicalFees: ['Challenge fee', 'No monthly subscription', 'Reset fee'], website: 'https://www.traderswithedge.com', category: 'forex' },
  { slug: 'the-trading-pit', name: 'The Trading Pit', payoutProcessor: 'Various', feeProcessor: 'Credit card', detection: 'auto', description: 'A multi-asset prop firm based in Liechtenstein offering evaluations across forex, futures, and crypto.', typicalFees: ['Challenge fee ($49-$999)', 'No monthly subscription', 'No reset fees'], website: 'https://www.thetradingpit.com', category: 'multi' },
  { slug: 'smart-prop-trader', name: 'Smart Prop Trader', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A forex prop firm offering one-step and two-step evaluations with up to 95% profit splits.', typicalFees: ['Challenge fee ($57-$557)', 'No monthly subscription', 'No reset fees'], website: 'https://www.smartproptrader.com', category: 'forex' },
  { slug: 'funding-pips', name: 'Funding Pips', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A forex prop firm with evaluation programs offering instant payouts and up to 90% profit splits.', typicalFees: ['Challenge fee ($36-$936)', 'No monthly subscription', 'No reset fees'], website: 'https://www.fundingpips.com', category: 'forex' },
  { slug: 'trade-the-pool', name: 'Trade The Pool', payoutProcessor: 'Various', feeProcessor: 'Credit card', detection: 'auto', description: 'A stock trading prop firm offering funded accounts for equities and options traders.', typicalFees: ['Challenge fee ($97-$397)', 'No monthly subscription', 'Commission per trade'], website: 'https://www.tradethepool.com', category: 'stocks' },
  { slug: 'alpha-capital', name: 'Alpha Capital', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A forex prop firm offering instant funding and evaluation programs with flexible trading rules.', typicalFees: ['Challenge fee', 'No monthly subscription', 'No reset fees'], website: 'https://www.alphacapitalgroup.com', category: 'forex' },
  { slug: 'maven', name: 'Maven', payoutProcessor: 'Rise', feeProcessor: 'Credit card', detection: 'auto', description: 'A forex prop firm offering evaluations with competitive pricing and profit splits up to 80%.', typicalFees: ['Challenge fee', 'No monthly subscription', 'Reset fee'], website: 'https://www.maventrading.com', category: 'forex' },
  { slug: 'brightfunded', name: 'BrightFunded', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A forex prop firm offering one-step and two-step evaluations with fast payouts and up to 90% profit splits.', typicalFees: ['Challenge fee ($47-$777)', 'No monthly subscription', 'No reset fees'], website: 'https://www.brightfunded.com', category: 'forex' },
  { slug: 'thinkcapital', name: 'ThinkCapital', payoutProcessor: 'Rise', feeProcessor: 'Credit card', detection: 'auto', description: 'A forex prop firm powered by ThinkMarkets, offering evaluations with institutional-grade execution.', typicalFees: ['Challenge fee', 'No monthly subscription', 'No reset fees'], website: 'https://www.thinkcapital.com', category: 'forex' },
  { slug: 'aquafunded', name: 'AquaFunded', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A forex prop firm offering evaluations with competitive pricing and up to 95% profit splits.', typicalFees: ['Challenge fee ($39-$399)', 'No monthly subscription', 'No reset fees'], website: 'https://www.aquafunded.com', category: 'forex' },
  { slug: 'blueberry-funded', name: 'Blueberry Funded', payoutProcessor: 'Rise', feeProcessor: 'Credit card', detection: 'auto', description: 'A forex prop firm backed by Blueberry Markets, offering evaluations with tight spreads and fast execution.', typicalFees: ['Challenge fee ($49-$599)', 'No monthly subscription', 'Reset fee'], website: 'https://www.blueberryfunded.com', category: 'forex' },
  { slug: 'e8-markets', name: 'E8 Markets', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A forex prop firm offering ELEV8 evaluation programs with up to 80% profit splits and bi-weekly payouts.', typicalFees: ['Challenge fee ($48-$588)', 'No monthly subscription', 'No reset fees'], website: 'https://www.e8markets.com', category: 'forex' },
  { slug: 'blue-guardian', name: 'Blue Guardian', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A forex prop firm offering evaluations with no time limits and up to 85% profit splits.', typicalFees: ['Challenge fee ($47-$547)', 'No monthly subscription', 'Reset fee'], website: 'https://www.blueguardian.com', category: 'forex' },
  { slug: 'instant-funding', name: 'Instant Funding', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A forex prop firm offering instant funding programs with no evaluation required and up to 90% profit splits.', typicalFees: ['Program fee ($250-$5,000)', 'No monthly subscription', 'No evaluation'], website: 'https://www.instantfunding.io', category: 'forex' },
  { slug: 'pipfarm', name: 'PipFarm', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A forex prop firm offering gamified evaluations with leaderboards, achievements, and up to 90% profit splits.', typicalFees: ['Challenge fee ($50-$500)', 'No monthly subscription', 'Reset fee'], website: 'https://www.pipfarm.com', category: 'forex' },
  { slug: 'audacity-capital', name: 'Audacity Capital', payoutProcessor: 'Direct Bank Transfer', feeProcessor: 'Credit card', detection: 'auto', description: 'A Dubai-based forex prop firm offering funded accounts through talent programs and evaluation challenges.', typicalFees: ['Challenge fee ($99-$599)', 'No monthly subscription', 'No reset fees'], website: 'https://www.audacitycapital.co.uk', category: 'forex' },
  { slug: 'for-traders', name: 'For Traders', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A forex prop firm offering evaluations with competitive pricing and flexible trading conditions.', typicalFees: ['Challenge fee ($47-$447)', 'No monthly subscription', 'Reset fee'], website: 'https://www.fortraders.com', category: 'forex' },
  { slug: 'finotive-funding', name: 'Finotive Funding', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A forex prop firm offering evaluations and direct funding programs with up to 95% profit splits.', typicalFees: ['Challenge fee ($49-$499)', 'No monthly subscription', 'Reset fee'], website: 'https://www.finotivefunding.com', category: 'forex' },
  { slug: 'atfunded', name: 'ATFunded', payoutProcessor: 'Rise', feeProcessor: 'Credit card', detection: 'auto', description: 'A forex prop firm offering evaluations with straightforward rules and competitive pricing.', typicalFees: ['Challenge fee', 'No monthly subscription', 'Reset fee'], website: 'https://www.atfunded.com', category: 'forex' },

  // Crypto
  { slug: 'hyrotrader', name: 'HyroTrader', payoutProcessor: 'Rise', feeProcessor: 'Credit card / crypto', detection: 'auto', description: 'A crypto-focused prop firm offering evaluations for cryptocurrency traders with up to 80% profit splits.', typicalFees: ['Challenge fee ($59-$499)', 'No monthly subscription', 'Reset fee'], website: 'https://www.hyrotrader.com', category: 'multi' },
];

export const payoutProcessors: PayoutProcessor[] = [
  { slug: 'rise', name: 'Rise (Riseworks)', description: 'The dominant payout processor for prop trading firms. Rise handles payouts for the majority of futures and forex prop firms. Funds appear as deposits from "Riseworks" or "Rise" in your bank statement.' },
  { slug: 'wise', name: 'Wise (TransferWise)', description: 'An international money transfer service used by some prop firms for cross-border payouts. Transactions appear as "Wise" or "TransferWise" on your bank statement.' },
  { slug: 'direct-bank-transfer', name: 'Wire / Direct Bank Transfer', description: 'Some prop firms send payouts directly via bank wire or ACH transfer. These appear as a direct deposit from the firm name on your bank statement.' },
  { slug: 'paypal', name: 'PayPal', description: 'An online payment platform used by some prop firms for payouts and fee collection. Transactions appear as "PayPal" followed by the firm name.' },
];

export function getCategoryLabel(category: PropFirm['category']): string {
  switch (category) {
    case 'futures': return 'Futures';
    case 'forex': return 'Forex';
    case 'stocks': return 'Stocks';
    case 'multi': return 'Multi-Asset';
  }
}
